<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Bach.Software.Application/Bach.Software.Application.csproj" />
    <ProjectReference Include="../Bach.Software.Core/Bach.Software.Core.csproj" />
    <ProjectReference Include="../Bach.Software.Infrastructure/Bach.Software.Infrastructure.csproj" />
  </ItemGroup>

</Project>
