sonar.projectKey=bach.software
sonar.projectName=Bach Software

sonar.sources=src/app
sonar.exclusions=**/*.test.ts,**/*.spec.ts,**/*.nuxt.test.ts,**/node_modules/**,**/.nuxt/**,**/dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
