/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageReadsFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type PageReads, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /analytics/pageReads/{url}
 */
export interface WithUrlItemRequestBuilder extends BaseRequestBuilder<WithUrlItemRequestBuilder> {
    /**
     * Returns the read analytics for a given page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageReads>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PageReads | undefined>;
    /**
     * Returns the read analytics for a given page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithUrlItemRequestBuilderUriTemplate = "{+baseurl}/analytics/pageReads/{url}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithUrlItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithUrlItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPageReadsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
