/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageLikesFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type PageLikes, type ProblemDetails, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /analytics/pageLikes
 */
export interface PageLikesRequestBuilder extends BaseRequestBuilder<PageLikesRequestBuilder> {
    /**
     * Returns the number of likes for a given page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageLikes>}
     * @throws {ValidationProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<PageLikesRequestBuilderGetQueryParameters> | undefined) : Promise<PageLikes | undefined>;
    /**
     * Returns the number of likes for a given page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PageLikesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns the number of likes for a given page.
 */
export interface PageLikesRequestBuilderGetQueryParameters {
    /**
     * The URL of the page to get like analytics for.
     */
    url?: string;
}
/**
 * Uri template for the request builder.
 */
export const PageLikesRequestBuilderUriTemplate = "{+baseurl}/analytics/pageLikes?url={url}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PageLikesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PageLikesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPageLikesFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
