/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PageReadsRequestBuilderRequestsMetadata, type PageReadsRequestBuilder } from './pageReads/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /analytics
 */
export interface AnalyticsRequestBuilder extends BaseRequestBuilder<AnalyticsRequestBuilder> {
    /**
     * The pageReads property
     */
    get pageReads(): PageReadsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AnalyticsRequestBuilderUriTemplate = "{+baseurl}/analytics";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AnalyticsRequestBuilderNavigationMetadata: Record<Exclude<keyof AnalyticsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    pageReads: {
        requestsMetadata: PageReadsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
