/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPageReadsFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, createValidationProblemDetailsFromDiscriminatorValue, type PageReads, type ProblemDetails, type ValidationProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /analytics/pageReads
 */
export interface PageReadsRequestBuilder extends BaseRequestBuilder<PageReadsRequestBuilder> {
    /**
     * Returns the read analytics for a given page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PageReads>}
     * @throws {ValidationProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<PageReadsRequestBuilderGetQueryParameters> | undefined) : Promise<PageReads | undefined>;
    /**
     * Returns the read analytics for a given page.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<PageReadsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns the read analytics for a given page.
 */
export interface PageReadsRequestBuilderGetQueryParameters {
    /**
     * The URL of the page to get read analytics for.
     */
    url?: string;
}
/**
 * Uri template for the request builder.
 */
export const PageReadsRequestBuilderUriTemplate = "{+baseurl}/analytics/pageReads?url={url}";
/**
 * Metadata for all the requests in the request builder.
 */
export const PageReadsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PageReadsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPageReadsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
